# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-09 17:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citation',
            name='bibliography',
        ),
        migrations.RemoveField(
            model_name='citationstone',
            name='citation',
        ),
        migrations.RemoveField(
            model_name='citationtree',
            name='citation',
        ),
        migrations.AddField(
            model_name='bibliography',
            name='page_range',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='citationstone',
            name='bibliography',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tree.Bibliography'),
        ),
        migrations.AddField(
            model_name='citationtree',
            name='bibliography',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tree.Bibliography'),
        ),
        migrations.AlterField(
            model_name='trees',
            name='crushing_strength',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trees',
            name='density',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trees',
            name='elastic_modulus',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trees',
            name='janka_hardness',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trees',
            name='rupture_modulus',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trees',
            name='tree_rad_high',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trees',
            name='tree_rad_low',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Citation',
        ),
    ]
